//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Scheduler.Resources {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Global {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Global() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Scheduler.Resources.Global", typeof(Global).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Current date is out of the limits set.
        /// </summary>
        public static string CurrentDateOutLimits {
            get {
                return ResourceManager.GetString("CurrentDateOutLimits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Proposed date can not be less than current date.
        /// </summary>
        public static string DateTimeCanNotBeLessThanCurrentDate {
            get {
                return ResourceManager.GetString("DateTimeCanNotBeLessThanCurrentDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Frequency must be greater than 0.
        /// </summary>
        public static string FrequencyMustBeGraterThanZero {
            get {
                return ResourceManager.GetString("FrequencyMustBeGraterThanZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a It is not possible to generate a execution date within the current date and limits set.
        /// </summary>
        public static string NotPossibleToGenerateExecDate {
            get {
                return ResourceManager.GetString("NotPossibleToGenerateExecDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Hourly.
        /// </summary>
        public static string RecurringTypes_1 {
            get {
                return ResourceManager.GetString("RecurringTypes_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Daily.
        /// </summary>
        public static string RecurringTypes_2 {
            get {
                return ResourceManager.GetString("RecurringTypes_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Weekly.
        /// </summary>
        public static string RecurringTypes_3 {
            get {
                return ResourceManager.GetString("RecurringTypes_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mounthly.
        /// </summary>
        public static string RecurringTypes_4 {
            get {
                return ResourceManager.GetString("RecurringTypes_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Yearly.
        /// </summary>
        public static string RecurringTypes_5 {
            get {
                return ResourceManager.GetString("RecurringTypes_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The recurring type is invalid.
        /// </summary>
        public static string RecurringTypes_Invalid {
            get {
                return ResourceManager.GetString("RecurringTypes_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Hour(s).
        /// </summary>
        public static string RecurringTypesUnits_1 {
            get {
                return ResourceManager.GetString("RecurringTypesUnits_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Day(s).
        /// </summary>
        public static string RecurringTypesUnits_2 {
            get {
                return ResourceManager.GetString("RecurringTypesUnits_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Week(s).
        /// </summary>
        public static string RecurringTypesUnits_3 {
            get {
                return ResourceManager.GetString("RecurringTypesUnits_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mounth(s).
        /// </summary>
        public static string RecurringTypesUnits_4 {
            get {
                return ResourceManager.GetString("RecurringTypesUnits_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Year(s).
        /// </summary>
        public static string RecurringTypesUnits_5 {
            get {
                return ResourceManager.GetString("RecurringTypesUnits_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a  Schedule will be used on {0} starting on {1}.
        /// </summary>
        public static string ScheduleDescription {
            get {
                return ResourceManager.GetString("ScheduleDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Occurs once..
        /// </summary>
        public static string ScheduleDescriptionOccursOnce {
            get {
                return ResourceManager.GetString("ScheduleDescriptionOccursOnce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Occurs every {0} {1}..
        /// </summary>
        public static string ScheduleDescriptionOccursRecurring {
            get {
                return ResourceManager.GetString("ScheduleDescriptionOccursRecurring", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a End date must be grater than start date..
        /// </summary>
        public static string StartDateGreaterThanEndDate {
            get {
                return ResourceManager.GetString("StartDateGreaterThanEndDate", resourceCulture);
            }
        }
    }
}
